### ISSUE TITLE
database.close is not a function

### ISSUE THREAD

**Issue by CallumHemsley** [fhellwig/sqlite-async#4]
Hello, I'm coming from sqlite3 as I want to async await, thanks for this awesome library. One thing I've noticed so far is that I can't seem to close my database sessions. The error I get when trying to do `database.close()` is that it's not a function. Any ideas?

```jsx
const database = require('sqlite-async');

database.open('./db/stats.db', database.OPEN_READWRITE | database.OPEN_CREATE)
  .then(db => {
    console.log('Connected to SQlite database.');
  })
  .catch(err => {
    console.log(err.message);
  });

database.close()
  .then(() => console.log("Close the database connection."))
  .catch(err => console.log(err.message));
```

**Comment by TheRealFaner** [comment]
Use [this](https://www.scriptol.com/sql/sqlite-async-await.php) template for async\await sqlite3. Is working correctly and most simple.

Use it how custom module and after create base db functions with connects and close.

Template:
```javascript
const sqlite = require('../modules/async-sqlite.module')

exports.all = async function (sql, params = []) {
    await sqlite.open(process.env.SQLITE_DB_PATH);
    const result = await sqlite.all(sql, params).then((val) => { return val });
    await sqlite.close();
    return result;
}
```
In `../modules/async-sqlite.module` I am copied code from [this template](https://www.scriptol.com/sql/sqlite-async-await.php).

Good luck!

**Comment by TheRealFaner** [comment]
> Hello, I'm coming from sqlite3 as I want to async await, thanks for this awesome library. One thing I've noticed so far is that I can't seem to close my database sessions. The error I get when trying to do `database.close()` is that it's not a function. Any ideas?
> 
> ```js-jsx
> const database = require('sqlite-async');
> 
> database.open('./db/stats.db', database.OPEN_READWRITE | database.OPEN_CREATE)
>   .then(db => {
>     console.log('Connected to SQlite database.');
>   })
>   .catch(err => {
>     console.log(err.message);
>   });
> 
> database.close()
>   .then(() => console.log("Close the database connection."))
>   .catch(err => console.log(err.message));
> ```

Use this template for async\await sqlite3. Is working correctly and most simple.

Use it how custom module and after create base db functions with connects and close.

Template:

const sqlite = require('../modules/async-sqlite.module')

exports.all = async function (sql, params = []) {
    await sqlite.open(process.env.SQLITE_DB_PATH);
    const result = await sqlite.all(sql, params).then((val) => { return val });
    await sqlite.close();
    return result;
}
In ../modules/async-sqlite.module I am copied code from this template.

Good luck!

**Comment by fhellwig** [comment]
When you require `sqlite-async`, you get back a `Database` *class* (upper-case `Database`, instead of `database`).

Given that, there are two options:

**Option 1**

When you call the **static** version of `open`, it returns a promise that is resolved with the database instance.

```javascript
const Database = require('./sqlite-async');

Database.open('./db/stats.db', Database.OPEN_READWRITE | Database.OPEN_CREATE)
  .then((db) => {
    console.log('Connected to SQlite database.');
    // Do stuff.
    db.close()
      .then(() => console.log('Close the database connection.'))
      .catch((err) => console.log(err.message));
  })
  .catch((err) => {
    console.log(err.message);
  });
```

**Option 2**

Here, we create a new database instance and then call `open` followed by calling `close`. (Note that you must do this within an `async` function - it won't work as top-level code in a Node module.)

```javascript
const database = new Database();

async function optionTwo() {
  await database
    .open('./db/stats.db', Database.OPEN_READWRITE | Database.OPEN_CREATE)
    .then((db) => {
      console.log('Connected to SQlite database.');
    })
    .catch((err) => {
      console.log(err.message);
    });
  //Do stuff.
  await database
    .close()
    .then(() => console.log('Close the database connection.'))
    .catch((err) => console.log(err.message));
}
```
