### ISSUE TITLE
how to use sqlite-async export csv file?

### ISSUE THREAD

**Issue by snailuncle** [fhellwig/sqlite-async#7]
![image](https://user-images.githubusercontent.com/24560326/93663992-2f167880-fa9e-11ea-9491-fe0cafd4df37.png)

![image](https://user-images.githubusercontent.com/24560326/93664047-92080f80-fa9e-11ea-9819-abfefc30e745.png)

i am use egg.js

**Comment by fhellwig** [comment]
Is there a bug, issue, or a change request? Not sure what is being asked here.

**Comment by fhellwig** [comment]
No response to comment from Dec 2, 2020. Closing it. Please feel free to open with more info.
